### ISSUE TITLE
バージョンダイアログが開かない

### ISSUE THREAD

**Issue by dhq-boiler** [dhq-boiler/boiler-s-Graphics#39]
バージョンダイアログを開こうとした時に例外が発生した。

Prism.Ioc.ContainerResolutionException: An unexpected error occurred while resolving 'System.Object', with the service name 'Version'
 ---> Unity.ResolutionFailedException: Exception has been thrown by the target of an invocation.
_____________________________________________________
Exception occurred while:
   on constructor:  Version()
(System.Object, boilersGraphics.Views.Version, Version)

 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Windows.Markup.XamlParseException: プロパティ 'Prism.Mvvm.ViewModelLocator.AutoWireViewModel' の Set で例外がスローされました。
 ---> Prism.Ioc.ContainerResolutionException: An unexpected error occurred while resolving 'boilersGraphics.ViewModels.VersionViewModel'
 ---> Unity.ResolutionFailedException: Exception has been thrown by the target of an invocation.
_____________________________________________________
Exception occurred while:
   on constructor:  VersionViewModel()

• while resolving:  VersionViewModel

 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.UnauthorizedAccessException: Access to the path 'C:\WINDOWS\system32\LICENSE' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at boilersGraphics.ViewModels.VersionViewModel.DownloadFile(WebClient client, String url, String file)
   at boilersGraphics.ViewModels.VersionViewModel.LicenseReadToEnd()
   at boilersGraphics.ViewModels.VersionViewModel..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Unity.Processors.ConstructorDiagnostic.<>c__DisplayClass14_0.<GetResolverDelegate>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.UnityContainer.<>c__DisplayClass113_0.<OptimizingFactory>b__0(BuilderContext& c)
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(BuilderContext& context)
   at Unity.UnityContainer.ExecuteValidatingPlan(BuilderContext& context)
   --- End of inner exception stack trace ---
   at Unity.UnityContainer.ExecuteValidatingPlan(BuilderContext& context)
   at Unity.UnityContainer.Unity.IUnityContainer.Resolve(Type type, String name, Resolv
Exception details truncated at 4000 chars.

**Comment by dhq-boiler** [comment]
v5.3.3で修正されたことを確認しました。
