### ISSUE TITLE
バージョン情報ダイアログを開くとエラー

### ISSUE THREAD

**Issue by dhq-boiler** [dhq-boiler/boiler-s-Graphics#57]
無料体験版をインストールした。
バージョン情報ダイアログを開くと例外が発生してアプリが落ちる。

Prism.Ioc.ContainerResolutionException: An unexpected error occurred while resolving 'System.Object', with the service name 'Version'
 ---> Unity.ResolutionFailedException: Exception has been thrown by the target of an invocation.
_____________________________________________________
Exception occurred while:
   on constructor:  Version()
(System.Object, boilersGraphics.Views.Version, Version)

 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Windows.Markup.XamlParseException: プロパティ 'Prism.Mvvm.ViewModelLocator.AutoWireViewModel' の Set で例外がスローされました。
 ---> Prism.Ioc.ContainerResolutionException: An unexpected error occurred while resolving 'boilersGraphics.ViewModels.VersionViewModel'
 ---> Unity.ResolutionFailedException: Exception has been thrown by the target of an invocation.
_____________________________________________________
Exception occurred while:
   on constructor:  VersionViewModel()

• while resolving:  VersionViewModel

 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.COMException (0x8000000E): 予期しないときにメソッドが呼び出されました。

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.DelegateExtensions.DynamicInvokeAbi(Delegate del, Object[] invoke_params)
   at ABI.Windows.Foundation.IAsyncOperationMethods`1.GetResults(IObjectReference _genericObj)
   at ABI.Windows.Foundation.IAsyncOperation`1.global::Windows.Foundation.IAsyncOperation<TResult>.GetResults()
   at boilersGraphics.ViewModels.VersionViewModel..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Unity.Processors.ConstructorDiagnostic.<>c__DisplayClass14_0.<GetResolverDelegate>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.UnityContainer.<>c__DisplayClass113_0.<OptimizingFactory>b__0(BuilderContext& c)
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(BuilderContext& context)
   at Unity.UnityContainer.ExecuteValidatingPlan(BuilderContext& context)
   --- End of inner exception stack trace ---
   at Unity.UnityContainer.ExecuteValidatingPlan(BuilderContext& context)
   at Unity.UnityContainer.Unity.IUnityContainer.Resolve(Type type, String name, ResolverOverride[] overrides)
   at Prism.Unity.UnityContainerExtension.Resolve(Type type, ValueTuple`2[] parameters)
   --- End of inner exception stack trace ---
   at Prism.Unity.UnityContainerExtension.Resolve(Type type, ValueTuple`2[] parameters)
   at Prism.Unity.UnityContainerExtension.Resolve(Type type)
   at Prism.PrismInitializationExtensions.<>c.<ConfigureViewModelLocator>b__0_0(Object view, Type type)
   at Prism.Mvvm.ViewModelLocationProvider.AutoWireViewModelChanged(Object view, Action`2 setDataContextCallback)
   at Prism.Mvvm.ViewModelLocator.AutoWireViewModelChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, Effec
Exception details truncated at 4000 chars.

**Comment by dhq-boiler** [comment]
試用版でなくてもフルライセンスを持っていても同じエラーがたまに出る。
