### ISSUE TITLE
Unable to cast object of type 'boilersGraphics.ViewModels.SnapPointViewModel' to type 'boilersGraphics.ViewModels.IRect'.

### ISSUE THREAD

**Issue by sofiosomkhisvili** [dhq-boiler/boiler-s-Graphics#92]
**Please describe the details of the error**

System.InvalidCastException
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at boilersGraphics.Models.Layer.UpdateAppearance(IEnumerable`1 items, Boolean backgroundIncluded)
   at boilersGraphics.Models.LayerTreeViewItemBase.UpdateAppearanceBothParentAndChild()
   at boilersGraphics.Models.Layer.<.ctor>b__1_10(Unit x)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 561
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 507
   at System.Reactive.ObserveOnObserverNew`1.<>c.<.cctor>b__17_0(IScheduler scheduler, ObserveOnObserverNew`1 self) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 497
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass11_0`1.<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by dhq-boiler** [comment]
I have identified the cause. It appears that Cast<IRect>() is being used where OfType<IRect>() should be used. Consequently, derived classes of SelectableDesignerItemViewModelBase that do not implement IRect are not accepted, resulting in an exception being thrown.

https://github.com/dhq-boiler/boiler-s-Graphics/blob/818b08bc19fb1dcd39064fbe81d50a0517425ef1/boilersGraphics/Models/Layer.cs#L142

To eliminate the cause, I believe using `OfType<IRect>()` instead of `Cast<IRect>()` should suffice, so I will make the correction.
